### ISSUE TITLE
Add a standard README

### ISSUE THREAD

**Issue by Rishabh04-02** [Nithmr/NithResultAppBackend#4]
Here is a sample minimal standard readme which one can refer [sample](https://github.com/RichardLitt/standard-readme/blob/master/example-readmes/minimal-readme.md)
OR you can refer this [sample2](https://github.com/Rishabh04-02/Elective-manager/blob/master/README.md)

**Comment by BrunoGomesCoelho** [comment]
#5

**Comment by BrunoGomesCoelho** [comment]
PR accepted, should be closed (I don't seem to have permission to do so)

**Comment by Rishabh04-02** [comment]
@BrunoGomesCoelho your PR has been merged, you can check it in the commits for the project.
